export const ORDER_REQUEST = "ORDER_REQUEST"
export const ORDER_SUCCESS = "ORDER_SUCCESS"
export const ORDER_FAIL = "ORDER_FAIL"

export const ORDER_DETAILS_REQUSET = "ORDER_DETAILS_REQUEST"
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS"
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL"

export const ORDER_PAY_REQUSET = "ORDER_PAY_REQUEST"
export const ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS"
export const ORDER_PAY_FAIL = "ORDER_PAY_FAIL"
export const ORDER_PAY_RESET = "PRDER_PAY_RESET"